version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:00'
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 10
    groups:
      go-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:30'
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - '*'
