schema = 4
vendorModulesTxt = "# github.com/PuerkitoBio/goquery v1.9.2\n## explicit; go 1.18\ngithub.com/PuerkitoBio/goquery\n# github.com/andybalholm/cascadia v1.3.2\n## explicit; go 1.16\ngithub.com/andybalholm/cascadia\n# github.com/aymanbagabas/go-osc52/v2 v2.0.1\n## explicit; go 1.16\ngithub.com/aymanbagabas/go-osc52/v2\n# github.com/charmbracelet/bubbles v0.19.0\n## explicit; go 1.18\ngithub.com/charmbracelet/bubbles/key\ngithub.com/charmbracelet/bubbles/progress\n# github.com/charmbracelet/bubbletea v1.1.0\n## explicit; go 1.18\ngithub.com/charmbracelet/bubbletea\n# github.com/charmbracelet/harmonica v0.2.0\n## explicit; go 1.16\ngithub.com/charmbracelet/harmonica\n# github.com/charmbracelet/lipgloss v0.13.0\n## explicit; go 1.18\ngithub.com/charmbracelet/lipgloss\n# github.com/charmbracelet/x/ansi v0.2.3\n## explicit; go 1.18\ngithub.com/charmbracelet/x/ansi\ngithub.com/charmbracelet/x/ansi/parser\n# github.com/charmbracelet/x/term v0.2.0\n## explicit; go 1.18\ngithub.com/charmbracelet/x/term\n# github.com/chzyer/readline v1.5.1\n## explicit; go 1.15\ngithub.com/chzyer/readline\n# github.com/davecgh/go-spew v1.1.1\n## explicit\ngithub.com/davecgh/go-spew/spew\n# github.com/erikgeiser/coninput v0.0.0-20211004153227-1c3628e74d0f\n## explicit; go 1.16\ngithub.com/erikgeiser/coninput\n# github.com/gdamore/encoding v1.0.1\n## explicit; go 1.9\ngithub.com/gdamore/encoding\n# github.com/gdamore/tcell/v2 v2.7.4\n## explicit; go 1.12\ngithub.com/gdamore/tcell/v2\ngithub.com/gdamore/tcell/v2/terminfo\ngithub.com/gdamore/tcell/v2/terminfo/a/aixterm\ngithub.com/gdamore/tcell/v2/terminfo/a/alacritty\ngithub.com/gdamore/tcell/v2/terminfo/a/ansi\ngithub.com/gdamore/tcell/v2/terminfo/b/beterm\ngithub.com/gdamore/tcell/v2/terminfo/base\ngithub.com/gdamore/tcell/v2/terminfo/c/cygwin\ngithub.com/gdamore/tcell/v2/terminfo/d/dtterm\ngithub.com/gdamore/tcell/v2/terminfo/dynamic\ngithub.com/gdamore/tcell/v2/terminfo/e/emacs\ngithub.com/gdamore/tcell/v2/terminfo/extended\ngithub.com/gdamore/tcell/v2/terminfo/f/foot\ngithub.com/gdamore/tcell/v2/terminfo/g/gnome\ngithub.com/gdamore/tcell/v2/terminfo/h/hpterm\ngithub.com/gdamore/tcell/v2/terminfo/k/konsole\ngithub.com/gdamore/tcell/v2/terminfo/k/kterm\ngithub.com/gdamore/tcell/v2/terminfo/l/linux\ngithub.com/gdamore/tcell/v2/terminfo/p/pcansi\ngithub.com/gdamore/tcell/v2/terminfo/r/rxvt\ngithub.com/gdamore/tcell/v2/terminfo/s/screen\ngithub.com/gdamore/tcell/v2/terminfo/s/simpleterm\ngithub.com/gdamore/tcell/v2/terminfo/s/sun\ngithub.com/gdamore/tcell/v2/terminfo/t/tmux\ngithub.com/gdamore/tcell/v2/terminfo/v/vt100\ngithub.com/gdamore/tcell/v2/terminfo/v/vt102\ngithub.com/gdamore/tcell/v2/terminfo/v/vt220\ngithub.com/gdamore/tcell/v2/terminfo/v/vt320\ngithub.com/gdamore/tcell/v2/terminfo/v/vt400\ngithub.com/gdamore/tcell/v2/terminfo/v/vt420\ngithub.com/gdamore/tcell/v2/terminfo/v/vt52\ngithub.com/gdamore/tcell/v2/terminfo/w/wy50\ngithub.com/gdamore/tcell/v2/terminfo/w/wy60\ngithub.com/gdamore/tcell/v2/terminfo/w/wy99_ansi\ngithub.com/gdamore/tcell/v2/terminfo/x/xfce\ngithub.com/gdamore/tcell/v2/terminfo/x/xterm\ngithub.com/gdamore/tcell/v2/terminfo/x/xterm_kitty\n# github.com/ktr0731/go-ansisgr v0.1.0\n## explicit; go 1.19\ngithub.com/ktr0731/go-ansisgr\n# github.com/ktr0731/go-fuzzyfinder v0.8.0\n## explicit; go 1.13\ngithub.com/ktr0731/go-fuzzyfinder\ngithub.com/ktr0731/go-fuzzyfinder/matching\ngithub.com/ktr0731/go-fuzzyfinder/scoring\n# github.com/lucasb-eyer/go-colorful v1.2.0\n## explicit; go 1.12\ngithub.com/lucasb-eyer/go-colorful\n# github.com/manifoldco/promptui v0.9.0\n## explicit; go 1.12\ngithub.com/manifoldco/promptui\ngithub.com/manifoldco/promptui/list\ngithub.com/manifoldco/promptui/screenbuf\n# github.com/mattn/go-isatty v0.0.20\n## explicit; go 1.15\ngithub.com/mattn/go-isatty\n# github.com/mattn/go-localereader v0.0.1\n## explicit\ngithub.com/mattn/go-localereader\n# github.com/mattn/go-runewidth v0.0.16\n## explicit; go 1.9\ngithub.com/mattn/go-runewidth\n# github.com/muesli/ansi v0.0.0-20230316100256-276c6243b2f6\n## explicit; go 1.17\ngithub.com/muesli/ansi\ngithub.com/muesli/ansi/compressor\n# github.com/muesli/cancelreader v0.2.2\n## explicit; go 1.17\ngithub.com/muesli/cancelreader\n# github.com/muesli/termenv v0.15.2\n## explicit; go 1.17\ngithub.com/muesli/termenv\n# github.com/nsf/termbox-go v1.1.1\n## explicit; go 1.15\ngithub.com/nsf/termbox-go\n# github.com/pkg/errors v0.9.1\n## explicit\ngithub.com/pkg/errors\n# github.com/pmezard/go-difflib v1.0.0\n## explicit\ngithub.com/pmezard/go-difflib/difflib\n# github.com/rivo/uniseg v0.4.7\n## explicit; go 1.18\ngithub.com/rivo/uniseg\n# github.com/stretchr/objx v0.5.2\n## explicit; go 1.20\ngithub.com/stretchr/objx\n# github.com/stretchr/testify v1.9.0\n## explicit; go 1.17\ngithub.com/stretchr/testify/assert\ngithub.com/stretchr/testify/mock\n# golang.org/x/net v0.28.0\n## explicit; go 1.18\ngolang.org/x/net/context\ngolang.org/x/net/html\ngolang.org/x/net/html/atom\n# golang.org/x/sync v0.8.0\n## explicit; go 1.18\ngolang.org/x/sync/errgroup\n# golang.org/x/sys v0.24.0\n## explicit; go 1.18\ngolang.org/x/sys/plan9\ngolang.org/x/sys/unix\ngolang.org/x/sys/windows\n# golang.org/x/term v0.23.0\n## explicit; go 1.18\ngolang.org/x/term\n# golang.org/x/text v0.17.0\n## explicit; go 1.18\ngolang.org/x/text/encoding\ngolang.org/x/text/encoding/internal/identifier\ngolang.org/x/text/transform\n# gopkg.in/yaml.v3 v3.0.1\n## explicit\ngopkg.in/yaml.v3\n"

[mod]
  [mod."github.com/PuerkitoBio/goquery"]
    version = "v1.9.2"
    hash = "sha256-9T/XF7YzCDt494E40p46BHZVNGnN4Duqlk/HsdbYEnI="
  [mod."github.com/andybalholm/cascadia"]
    version = "v1.3.2"
    hash = "sha256-Nc9SkqJO/ecincVcUBFITy24TMmMGj5o0Q8EgdNhrEk="
  [mod."github.com/aymanbagabas/go-osc52/v2"]
    version = "v2.0.1"
    hash = "sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg="
  [mod."github.com/charmbracelet/bubbles"]
    version = "v0.19.0"
    hash = "sha256-eN8QmTZjHMzUgJ877IFPsGjS5WEgvMPAgPHytTwtitU="
  [mod."github.com/charmbracelet/bubbletea"]
    version = "v1.1.0"
    hash = "sha256-LPOpM47jiLV+FBvDp3Ry4HXQMZOCSeJTWe22w4KL35A="
  [mod."github.com/charmbracelet/harmonica"]
    version = "v0.2.0"
    hash = "sha256-fi5N0IXhSbbYHdSZFngCfpT4kdiEaKedqj8YpnlvX0o="
  [mod."github.com/charmbracelet/lipgloss"]
    version = "v0.13.0"
    hash = "sha256-80A5GLx5cG3pd9LMN6edv27x6R2GQWDFdWTbcLFtcbo="
  [mod."github.com/charmbracelet/x/ansi"]
    version = "v0.2.3"
    hash = "sha256-JYjiEPdFsI/RtlUyMoOtGUlXo1/fmf5Oh8NMGBRaIdg="
  [mod."github.com/charmbracelet/x/term"]
    version = "v0.2.0"
    hash = "sha256-eIsmNg/ktYEFWG9j/z2FuD+iizkV+HGLrUvor7Xkqlo="
  [mod."github.com/chzyer/readline"]
    version = "v1.5.1"
    hash = "sha256-6wKd6/JZ9/O7FwSyNKE3KOt8fVPZEunqbTHQUxlOUNc="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/erikgeiser/coninput"]
    version = "v0.0.0-20211004153227-1c3628e74d0f"
    hash = "sha256-OWSqN1+IoL73rWXWdbbcahZu8n2al90Y3eT5Z0vgHvU="
  [mod."github.com/gdamore/encoding"]
    version = "v1.0.1"
    hash = "sha256-EfY23Sy/jrcPlw4gKvvVgUicxEcD6iw1QNMPay9ZBhQ="
  [mod."github.com/gdamore/tcell/v2"]
    version = "v2.7.4"
    hash = "sha256-zRZ132vNob63Qd8u2KJ9xywUj6Tb0d6a5JYi558WYhU="
  [mod."github.com/ktr0731/go-ansisgr"]
    version = "v0.1.0"
    hash = "sha256-MTBJ3fxu6CQrND7dO9xwFHfFuq7PllQsgfDTh2caVsI="
  [mod."github.com/ktr0731/go-fuzzyfinder"]
    version = "v0.8.0"
    hash = "sha256-P/QNhs+9z2EIyQJaO6flGaZtD2G05ZMABaNiEkv4Gq0="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.2.0"
    hash = "sha256-Gg9dDJFCTaHrKHRR1SrJgZ8fWieJkybljybkI9x0gyE="
  [mod."github.com/manifoldco/promptui"]
    version = "v0.9.0"
    hash = "sha256-Fe2OPoyRExZejwtUBivKhfJAJW7o9b1eyYpgDlWQ1No="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-localereader"]
    version = "v0.0.1"
    hash = "sha256-JlWckeGaWG+bXK8l8WEdZqmSiTwCA8b1qbmBKa/Fj3E="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.16"
    hash = "sha256-NC+ntvwIpqDNmXb7aixcg09il80ygq6JAnW0Gb5b/DQ="
  [mod."github.com/muesli/ansi"]
    version = "v0.0.0-20230316100256-276c6243b2f6"
    hash = "sha256-qRKn0Bh2yvP0QxeEMeZe11Vz0BPFIkVcleKsPeybKMs="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/muesli/termenv"]
    version = "v0.15.2"
    hash = "sha256-Eum/SpyytcNIchANPkG4bYGBgcezLgej7j/+6IhqoMU="
  [mod."github.com/nsf/termbox-go"]
    version = "v1.1.1"
    hash = "sha256-Fxk9s3vKmXO3uWmpneN1iZQ+nCbUEZLWShDyeJcwhvM="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.2"
    hash = "sha256-VKYxrrFb1nkX6Wu3tE5DoP9+fCttwSl9pgLN6567nck="
  [mod."github.com/stretchr/testify"]
    version = "v1.9.0"
    hash = "sha256-uUp/On+1nK+lARkTVtb5RxlW15zxtw2kaAFuIASA+J0="
  [mod."golang.org/x/net"]
    version = "v0.28.0"
    hash = "sha256-WdH/mgsX/CB+CiYtXEwJAXHN8FgtW2YhFcWwrrHNBLo="
  [mod."golang.org/x/sync"]
    version = "v0.8.0"
    hash = "sha256-usvF0z7gq1vsX58p4orX+8WHlv52pdXgaueXlwj2Wss="
  [mod."golang.org/x/sys"]
    version = "v0.24.0"
    hash = "sha256-P0fsA+qy9taYHWPTtCs5XmrJ1i8tWfvkno+PNuc2elw="
  [mod."golang.org/x/term"]
    version = "v0.23.0"
    hash = "sha256-ECmmK3Wc0g/zUy5wAokj7ItRsUi6eoqSe9s9Uhcwu90="
  [mod."golang.org/x/text"]
    version = "v0.17.0"
    hash = "sha256-R8JbsP7KX+KFTHH7SjRnUGCdvtagylVOfngWEnVSqBc="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
